name: nfc_wallet
description: NFC wallet application to store physical copies of nfc cards

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_nfc_reader:
    git:
      url: https://github.com/semakers/flutter-nfc-reader.git
      ref: master

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true