name: nfc_wallet
description: NFC wallet application to store physical copies of nfc cards

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  animated_gesture_detector: ^1.0.0

  uuid: 3.0.4
  hive: ^2.2.3
  shared_preferences: ^2.0.15
  path_provider: ^2.0.2

  nfc_emulator: ^2.0.0-nullsafety.0
  nfc_manager: ^3.1.1

  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.4
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true